blueprints/boards.py
import time

from flask import Blueprint, render_template, redirect, url_for, flash, request, make_response, session
from flask_restful import reqparse
from markdown import markdown
from werkzeug.http import parse_etags

import cache
import captchouli
import renderer
from model.Media import storage
from model.Board import Board
from model.BoardList import BoardList
from model.BoardListCatalog import BoardCatalog
from model.Post import render_for_catalog
from model.Slip import get_slip, get_slip_bitmask
from model.Tag import Tag
from shared import db, app


def get_tags(threads):
    tag_names = set()
    for thread in threads:
        for tag in thread["tags"]:
            tag_names.add(tag)
    tag_styles = {}
    found_tags = Tag.query.filter(Tag.name.in_(tag_names)).all()
    for tag in found_tags:
        tag_styles[tag.name] = {}
        if tag.bg_style:
            tag_styles[tag.name]["bg_style"] = tag.bg_style
        if tag.text_style:
            tag_styles[tag.name]["text_style"] = tag.text_style
    return tag_styles


boards_blueprint = Blueprint('boards', __name__, template_folder='template')


@boards_blueprint.route("/")
def list():
    boards = BoardList().get()
    for board in boards:
        board["catalog_url"] = url_for("boards.catalog", board_id=board["id"])
        if board["media"]:
            board["thumb_url"] = storage.get_thumb_url(board["media"])
    return renderer.render_board_index(boards)


@boards_blueprint.route("/<int:board_id>")
def catalog(board_id):
    current_theme = session.get("theme") or app.config.get("DEFAULT_THEME") or "stock"
    response_cache_key = "board-%d-%d-%s-render" % (board_id, get_slip_bitmask(), current_theme)
    cache_connection = cache.Cache()
    cached_response_body = cache_connection.get(response_cache_key)
    etag_value = "%s-%f" % (response_cache_key, time.time())
    etag_cache_key = "%s-etag" % response_cache_key
    if cached_response_body:
        etag_header = request.headers.get("If-None-Match")
        current_etag = cache_connection.get(etag_cache_key)
        if etag_header:
            parsed_etag = parse_etags(etag_header)
            if parsed_etag.contains_weak(current_etag):
                return make_response("", 304)
        cached_response = make_response(cached_response_body)
        cached_response.set_etag(current_etag, weak=True)
        cached_response.headers["Cache-Control"] = "public,must-revalidate"
        return cached_response
    threads = BoardCatalog().retrieve(board_id)
    board = db.session.query(Board).get(board_id)
    board_name = board.name
    render_for_catalog(threads)
    tag_styles = get_tags(threads)
    catalog_data = {}
    catalog_data["tag_styles"] = tag_styles
    for thread in threads:
        del thread["last_updated"]
    catalog_data["threads"] = threads
    extra_data = {}
    if app.config.get("CAPTCHA_METHOD") == "CAPTCHOULI":
        extra_data = renderer.captchouli_to_json(captchouli.request_captcha())
    template = renderer.render_catalog(catalog_data, board_name, board_id, extra_data)
    uncached_response = make_response(template)
    uncached_response.set_etag(etag_value, weak=True)
    uncached_response.headers["Cache-Control"] = "public,must-revalidate"
    cache_connection.set(response_cache_key, template)
    cache_connection.set(etag_cache_key, etag_value)
    return uncached_response


@boards_blueprint.route("/rules", defaults={'board_id': None})
@boards_blueprint.route("/rules/<int:board_id>")
def rules(board_id):
    if board_id is None:
        return redirect(url_for('main.rules'))
    board = db.session.query(Board).filter(Board.id == board_id).one()
    return render_template("rules.html", board=board, markdown=markdown)


@boards_blueprint.route("/admin/<int:board_id>")
def admin(board_id):
    if get_slip() and get_slip().is_admin:
        board = db.session.query(Board).filter(Board.id == board_id).one()
        return render_template("board-admin.html", board=board)
    else:
        flash("Only admins can access board administration!")
        return redirect(url_for("boards.catalog", board_id=board_id))


@boards_blueprint.route("/admin/<int:board_id>", methods=["POST"])
def admin_update(board_id):
    if get_slip() is None or get_slip().is_admin is False:
        flash("Only admins can access board administration!")
        return redirect(url_for("boards.catalog", board_id=board_id))
    board = db.session.query(Board).filter(Board.id == board_id).one()
    parser = reqparse.RequestParser()
    parser.add_argument("name", type=str, required=True)
    parser.add_argument("rules", type=str, required=True)
    parser.add_argument("max-threads", type=int, required=True)
    parser.add_argument("mimetypes", type=str, required=True)
    args = parser.parse_args()
    board.name = args["name"]
    board.rules = args["rules"]
    board.max_threads = args["max-threads"]
    board.mimetypes = args["mimetypes"]
    db.session.add(board)
    db.session.commit()
    return redirect(url_for("boards.catalog", board_id=board_id))

blueprints/main.py
import time

from flask import Blueprint, render_template, make_response, request, session
from markdown import markdown
from werkzeug.http import parse_etags

import renderer
import cache
from blueprints.boards import get_tags
from model.Firehose import Firehose
from model.Slip import get_slip_bitmask
from shared import app

main_blueprint = Blueprint('main', __name__, template_folder='template')


@main_blueprint.route("/")
def index():
    cache_connection = cache.Cache()
    current_theme = session.get("theme") or app.config.get("DEFAULT_THEME") or "stock"
    response_cache_key = "firehose-%d-%s-render" % (get_slip_bitmask(), current_theme)
    cached_response_body = cache_connection.get(response_cache_key)
    etag_value = "%s-%f"  % (response_cache_key, time.time())
    etag_cache_key = "%s-etag" % response_cache_key
    if cached_response_body:
        etag_header = request.headers.get("If-None-Match")
        current_etag = cache_connection.get(etag_cache_key)
        if etag_header:
            parsed_etag = parse_etags(etag_header)
            if parsed_etag.contains_weak(current_etag):
                return make_response("", 304)
        cached_response = make_response(cached_response_body)
        cached_response.set_etag(current_etag, weak=True)
        cached_response.headers["Cache-Control"] = "public,must-revalidate"
        return cached_response
    greeting = open("deploy-configs/index-greeting.html").read()
    threads = Firehose().get_impl()
    # fix to avoid needing to serialize the datetime
    for thread in threads:
        del thread["last_updated"]
    tag_styles = get_tags(threads)
    firehose_data = {
        "threads": threads,
        "tag_styles": tag_styles}
    template = renderer.render_firehose(firehose_data, greeting)
    #template = render_template("index.html", greeting=greeting, threads=threads, tag_styles=tag_styles)
    uncached_response = make_response(template)
    uncached_response.set_etag(etag_value, weak=True)
    uncached_response.headers["Cache-Control"] = "public,must-revalidate"
    cache_connection.set(response_cache_key, template)
    cache_connection.set(etag_cache_key, etag_value)
    return uncached_response


@main_blueprint.route("/rules")
def rules():
    return render_template("rules.html", markdown=markdown)


@main_blueprint.route("/faq")
def faq():
    return render_template("faq.html")

blueprints/theme.py
from flask import Blueprint, session, redirect, request


theme_blueprint = Blueprint('theme', __name__, template_folder='template')


@theme_blueprint.route("/set-theme", methods=["POST"])
def set_theme():
    theme_name = request.form["selected-theme"]
    session["theme"] = theme_name
    return redirect(request.referrer)

blueprints/threads.py
import time

from flask import Blueprint, render_template, redirect, url_for, flash, request, copy_current_request_context, session, make_response
from werkzeug.http import parse_etags

import cache
import captchouli
import cooldown
from model.Media import upload_size, storage
from model.Board import Board
from model.NewPost import NewPost
from model.NewThread import NewThread
from model.Post import Post, render_for_threads
from model.PostRemoval import PostRemoval
from model.PostReplyPattern import url_for_post
from model.Poster import Poster
from model.Slip import get_slip, get_slip_bitmask
from model.SubmissionError import SubmissionError
from model.Thread import Thread
from model.ThreadPosts import ThreadPosts
from post import InvalidMimeError, CaptchaError
import renderer
from shared import db, app
from thread import invalidate_board_cache


threads_blueprint = Blueprint('threads', __name__, template_folder='template')
threads_blueprint.add_app_template_global(url_for_post)


@app.context_processor
def get_captchouli():
    def _get_captchouli():
        return captchouli.request_captcha()
    return dict(get_captchouli=_get_captchouli)


@threads_blueprint.route("/new/<int:board_id>")
def new(board_id):
    extra_data = {}
    if app.config.get("CAPTCHA_METHOD") == "CAPTCHOULI":
        extra_data = renderer.captchouli_to_json(captchouli.request_captcha())
    return renderer.render_new_thread_form(board_id, extra_data)


@threads_blueprint.route("/new", methods=["POST"])
def submit():
    try:
        thread = NewThread().post()
        return redirect(url_for("threads.view", thread_id=thread.id))
    except SubmissionError as e:
        flash(str(e.args[0]))
        return redirect(url_for("threads.new", board_id=e.args[1]))
    except InvalidMimeError as e:
        flash("Can't post attachment with MIME type \"%s\" on this board!" % e.args[0])
        return redirect(url_for("threads.new", board_id=e.args[1]))
    except CaptchaError as e:
        flash("CAPTCHA error: %s" % e.args[0])
        return redirect(url_for("threads.new", board_id=e.args[1]))


@threads_blueprint.route("/<int:thread_id>")
def view(thread_id):
    thread = db.session.query(Thread).filter(Thread.id == thread_id).one()
    thread.views += 1
    db.session.add(thread)
    db.session.commit()
    current_theme = session.get("theme") or app.config.get("DEFAULT_THEME") or "stock"
    response_cache_key = "thread-%d-%d-%s-render" % (thread_id, get_slip_bitmask(), current_theme)
    cache_connection = cache.Cache()
    view_key = "thread-%d-views" % thread_id
    cached_views = cache_connection.get(view_key)
    fetch_from_cache = True
    if cached_views is None:
        fetch_from_cache = False
    else:
        cached_views = int(cached_views)
    if fetch_from_cache and (thread.views / cached_views) >= app.config.get("CACHE_VIEW_RATIO", 0):
        fetch_from_cache = False
    etag_value = "%s-%f" % (response_cache_key, time.time())
    etag_cache_key = "%s-etag" % response_cache_key
    if fetch_from_cache:
        etag_header = request.headers.get("If-None-Match")
        current_etag = cache_connection.get(etag_cache_key)
        if etag_header:
            parsed_etag = parse_etags(etag_header)
            if parsed_etag.contains_weak(current_etag):
                 return make_response("", 304)
        cache_response_body = cache_connection.get(response_cache_key)
        if cache_response_body is not None:
            cached_response = make_response(cache_response_body)
            cached_response.set_etag(current_etag, weak=True)
            cached_response.headers["Cache-Control"] = "public,must-revalidate"
            return cached_response
    posts = ThreadPosts().retrieve(thread_id)
    render_for_threads(posts)
    board = db.session.query(Board).get(thread.board)
    num_posters = db.session.query(Poster).filter(Poster.thread == thread_id).count()
    num_media = thread.num_media()
    reply_urls = _get_reply_urls(posts)
    thread_data = {}
    for post in posts:
        post["datetime"] = post["datetime"].strftime("%a, %d %b %Y %H:%M:%S UTC")
        if post["media"]:
            post["media_url"] = storage.get_media_url(post["media"], post["media_ext"])
            post["thumb_url"] = storage.get_thumb_url(post["media"])
    thread_data["posts"] = posts
    extra_data = {}
    if app.config.get("CAPTCHA_METHOD") == "CAPTCHOULI":
        extra_data = renderer.captchouli_to_json(captchouli.request_captcha())
    template = renderer.render_thread(thread_data, thread_id, extra_data)
    uncached_response = make_response(template)
    uncached_response.set_etag(etag_value, weak=True)
    uncached_response.headers["Cache-Control"] = "public,must-revalidate"
    cache_connection.set(view_key, str(thread.views))
    cache_connection.set(response_cache_key, template)
    cache_connection.set(etag_cache_key, etag_value)
    return uncached_response


@threads_blueprint.route("/<int:thread_id>/delete")
def delete(thread_id):
    if not get_slip() or not (get_slip().is_admin or get_slip().is_mod):
        flash("Only moderators and admins can delete threads!")
        return redirect(url_for("threads.view", thread_id=thread_id))
    thread = db.session.query(Thread).filter(Thread.id == thread_id).one()
    board_id = thread.board
    ThreadPosts().delete(thread_id)
    invalidate_board_cache(board_id)
    flash("Thread deleted!")
    return redirect(url_for("boards.catalog", board_id=board_id))


@threads_blueprint.route("/<int:thread_id>/move")
def move(thread_id):
    if not get_slip() or not (get_slip().is_admin or get_slip().is_mod):
        flash("Only moderators and admins can move threads!")
        return redirect(url_for("threads.view", thread_id=thread_id))
    return render_template("thread-move.html", thread_id=thread_id)


@threads_blueprint.route("/<int:thread_id>/move", methods=["POST"])
def move_submit(thread_id):
    if not get_slip() or not (get_slip().is_admin or get_slip().is_mod):
        flash("Only moderators and admins can move threads!")
        return redirect(url_for("threads.view", thread_id=thread_id))
    thread = Thread.query.get(thread_id)
    old_board = thread.board
    new_board = Board.query.filter(Board.name == request.form["board"]).one()
    thread.board = new_board.id
    db.session.add(thread)
    db.session.commit()
    invalidate_board_cache(old_board)
    invalidate_board_cache(new_board)
    flash("Thread moved!")
    return redirect(url_for("threads.view", thread_id=thread_id))
    

@threads_blueprint.route("/<int:thread_id>/new")
def new_post(thread_id):
    extra_data = {}
    if app.config.get("CAPTCHA_METHOD") == "CAPTCHOULI":
        extra_data = renderer.captchouli_to_json(captchouli.request_captcha())
    return renderer.render_new_post_form(thread_id, extra_data)


@threads_blueprint.route("/<int:thread_id>/new", methods=["POST"])
def post_submit(thread_id):
    try:
        NewPost().post(thread_id)
    except InvalidMimeError as e:
        flash("Can't post attachment with MIME type \"%s\" on this board!" % e.args[0])
        return redirect(url_for("threads.new_post", thread_id=thread_id))
    except CaptchaError as e:
        flash("CAPTCHA error: %s" % e.args[0])
        return redirect(url_for("threads.new_post", thread_id=thread_id))
    return redirect(url_for("threads.view", thread_id=thread_id) + "#thread-bottom")


@threads_blueprint.route("/post/<int:post_id>/delete")
def delete_post(post_id):
    if not get_slip() or not (get_slip().is_admin or get_slip().is_mod):
        flash("Only moderators and admins can delete posts!")
        return redirect(url_for_post(post_id))
    thread = db.session.query(Thread).filter(Thread.posts.any(Post.id == post_id)).one()
    thread_id = thread.id
    PostRemoval().delete(post_id)
    flash("Post deleted!")
    return redirect(url_for("threads.view", thread_id=thread_id))


@threads_blueprint.route("/post/<int:post_id>")
def render_post(post_id):
    raw_post = db.session.query(Post).get(post_id)
    thread_id = raw_post.thread
    thread = db.session.query(Thread).get(thread_id)
    dummy_array = ThreadPosts()._json_friendly([raw_post], thread)
    render_for_threads(dummy_array)
    post = dummy_array[0]
    reply_urls = _get_reply_urls([post])
    # TODO: properly set is_op, will be False most times, so set to that for now
    is_op = False
    return render_template("post-view-single.html", post=post, thread_id=thread_id, is_op=is_op, reply_urls=reply_urls)


@threads_blueprint.route("/<int:thread_id>/gallery")
def view_gallery(thread_id):
    posts = ThreadPosts().retrieve(thread_id)
    for post in posts:
        # TODO: either streamline what gets sent to the frontend
        # or automatically serialize datetimes so the below isn't necessary
        del post["datetime"]
        post["thumb_url"] = storage.get_thumb_url(post["media"])
        post["media_url"] = storage.get_media_url(post["media"], post["media_ext"])
    thread = db.session.query(Thread).filter(Thread.id == thread_id).one()
    board = db.session.query(Board).get(thread.board)
    return renderer.render_thread_gallery(board, thread_id, posts)


def _get_reply_urls(posts):
    reply_ids = set()
    for post in posts:
        for reply in post["replies"]:
            reply_ids.add(reply)
    reply_urls = dict(map(lambda i: (i, url_for_post(i)), reply_ids))
    return reply_urls

blueprints/upload.py
import datetime

from flask import Blueprint, current_app, send_from_directory

from model.Media import Media, storage
from shared import db


upload_blueprint = Blueprint('upload', __name__, template_folder='template')


@upload_blueprint.route("/<int:media_id>")
def file(media_id):
    return storage.get_attachment(media_id)


@upload_blueprint.route("/thumb/<int:media_id>")
def thumb(media_id):
    return storage.get_thumbnail(media_id)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="{{ get_current_theme_path() }}">
    <script src="{{ static_resource("jquery/jquery.min.js") }}"></script>
    <script src="{{ static_resource("popperjs/umd/popper.min.js") }}"></script>
    <script src="{{ static_resource("bootstrap/bootstrap.min.js") }}"></script>

    <!-- Fontawesome -->
    <link rel="stylesheet" href="{{ static_resource("fontawesome/all.min.css") }}">
	{% block head %}{% endblock %}
    <title>{{ instance_name() }} - {% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top mb-2">
    <a class="navbar-brand" href="{{ url_for("main.index") }}">{{ instance_name() }}</a>
    <script>
			 document.write('<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#site-nav"> \
				 <span class="navbar-toggler-icon"></span> \
				 </button>')



    </script>
    <div id="site-nav" class="navbar-nav">
        {% block navbar %}{% endblock %}
		{% if board is defined %}
			<a href="{{ url_for("boards.catalog", board_id=board["id"]) }}" class="nav-item nav-link">/{{ board["name"] }}/ Catalog</a>
		{% endif %}
        <a href="{{ url_for("boards.list") }}" class="nav-item nav-link">Boards</a>
        <a href="{{ url_for("slip.landing") }}" class="nav-item nav-link">Slip</a>
        {% if board is not defined %}
        <a href="{{ url_for("main.rules") }}" class="nav-item nav-link">Rules</a>
        {% else %}
        <a href="{{ url_for("boards.rules", board_id=board.id) }}" class="nav-item nav-link">Rules</a>
        {% endif %}
        <a href="{{ url_for("main.faq") }}" class="nav-item nav-link">FAQ</a>
        <div class="navbar-nav ml-auto">
            {% block navbar_right %}{% endblock %}
        </div>
    </div>
    <script>
				$("#site-nav").addClass("collapse navbar-collapse")



    </script>
</nav>
{% with flashes = get_flashed_messages() %}
{% if flashes %}
<div class="container">
    {% for message in flashes %}
    <div class="alert alert-primary">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
{% block content %}{% endblock %}
<hr>
<div class="theme-selector">
	<form method="post" enctype="multipart/form-data" action="{{ url_for("theme.set_theme") }}">
		<select name="selected-theme">
			{% for theme_name in get_themes() %}
				{% if theme_name == get_current_theme() %}
					<option value="{{ theme_name }}" selected="selected">{{ theme_name }}</option>
				{% else %}
					<option value="{{ theme_name }}">{{ theme_name }}</option>
				{% endif %}
			{% endfor %}
		</select>
		<button id="theme-submit" type="submit" class="btn btn-primary">Select theme</button>
	</form>
</div>
<div class="container-fluid">
    {% block footer %}{% endblock %}
    <p class="text-center text-muted">
        <small>Powered by <a href="https://github.com/DangerOnTheRanger/maniwani">Maniwani</a>!</small>
    </p>
</div>
</body>
</html>

templates/board-admin.html
{%- extends "base.html" %}
{% block title %}
administrate board
{% endblock %}
{% block content %}
<div class="container">
    <form method="post">
        <div class="form-group">
            <label for="name">Board name</label>
            <input type="text" id="name" name="name" class="form-control" value="{{ board.name }}">
        </div>
        <div class="form-group">
            <label for="rules">Board rules</label>
            <textarea id="rules" name="rules" class="form-control">{{ board.rules | safe }}</textarea>
            <small class="form-text text-muted">Board rules are written in Markdown.</small>
        </div>
		<div class="form-group">
			<label for="max-threads">Max threads</label>
			<input type="text" id="max-threads" name="max-threads" class="form-control" value="{{ board.max_threads }}">
		</div>
		<div class="form-group">
			<label for="mimetypes">Allowed MIME types</label>
			<input type="text" id="mimetypes" name="mimetypes" class="form-control" value="{{ board.mimetypes | safe }}">
		</div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

templates/board-index.html
{%- extends "base.html" %}
{% block title %}
	board index
{% endblock %}
{% block head %}
	<style>
	 .board {
		 margin: 0.1em;
	 }
	 .board-container {
		 position: relative;
		 text-align: center;
	 }
	 .board-media {
		 opacity: 0.4;
	 }
	 .board-name {
		 font-size: 4em;
	 }
	 .over-image {
		 position: absolute;
		 top: 50%;
		 left: 50%;
		 transform: translate(-50%, -50%);
	 }
	 .no-image {
		 vertical-align: -50%;
	 }
	 .dummy-media {
		 width: 280px;
		 height: auto;
	 }
	 @media (min-width: 576px) {
		 .board, board-sizer {
			 width: 95%;
		 }
	 }
	 @media (min-width: 768px) {
		 .board, board-sizer {
			 width: 49%;
		 }
	 }
	 @media (min-width: 992px) {
		 .board, board-sizer {
			 width: 32%;
		 }
	 }
	 @media (min-width: 1200px) {
		 .board, board-sizer {
			 width: 19%;
		 }
	 }



	</style>
	<script src="{{ static_resource("imagesloaded/imagesloaded.pkgd.min.js") }}"></script>
	<script src="{{ static_resource("masonry/masonry.pkgd.min.js") }}"></script>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div id="grid" style="display: flex; flex-wrap: wrap;">
        <script>
			 document.write('<div class="board-sizer"></div>')



        </script>
        {% for board in boards %}
        <a href="{{ url_for("boards.catalog", board_id=board["id"]) }}" class="board bg-light border rounded">
        <div class="board-container">
            {% if board["media"] %}
            <img src="{{ url_for("upload.thumb", media_id=board["media"]) }}" class="board-media img-fluid">
            <span class="board-name over-image text-dark">/{{ board["name"] }}/</span>
            {% else %}
            <div class="dummy-media"></div>
            <span class="board-name text-dark align-middle no-image">/{{ board["name"] }}/</span>
            {% endif %}
        </div>
        </a>
        {% endfor %}
    </div>
    <script>
		 var grid = $("#grid")
		 grid.imagesLoaded( function() {
			 grid.masonry({
				 columnWidth: '.board-sizer',
				 itemSelector: '.board',
				 percentPosition: true,
				 horizontalOrder: true
			 })
		 })



    </script>
</div>
{% endblock %}

templates/catalog.html
{%- extends "base.html" %}
{% block title %}
/{{ board_name }}/ catalog
{% endblock %}
{% block navbar %}
<a href="{{ url_for("threads.new", board_id=board["id"]) }}" class="nav-item nav-link">New thread</a>
{% if get_slip() and get_slip().is_admin %}
<a href="{{ url_for("boards.admin", board_id=board["id"]) }}" class="nav-item nav-link">Admin</a>
{% endif %}
{% endblock %}
{% block content %}
{% import "catalog-view.html" as catalog_view with context %}
{{ catalog_view.catalog_view(threads, tag_styles) }}
{% endblock %}

templates/faq.html
{%- extends "base.html" %}
{% block title %}
frequently asked questions
{% endblock %}
{% block content %}
<div class="container">
    <h1 id="whats-an-imageboard">What's an imageboard?</h1>
    <p class="lead">An imageboard is kind of like a forum.</p>
    <p>But a bit more image-focused, and temporary in nature. You post images you like to spark
        discussion and get others to post similar images. Also, unlike a forum, threads don't last
        indefinitely. Old threads that have either been around for a certain period of time, or that
        nobody is posting in any longer, get removed to make way for new threads. This helps keep
        discussion focused on new and relevant things and prevent the site from getting tunnel vision
        on any particular topic. If you don't see anyone discussing a topic you'd like to see talked
        about, just make a thread!</p>
    <p>You might also be wondering why everyone is anonymous, especially if you're used to some of
        the larger social media networks out there. There's a pretty good reason for this, actually:
        The content of each post should be more important than the identity of whoever posted it.
        With everyone being anonymous, a lot of harmful by-products of usernames on other sites are
        no longer possible:
    <ul>
        <li>Trawling a user's post history to bring up irrelevant things to discredit a post or
            argument of theirs
        </li>
        <li>Forming a cult of personality around one user or a group of users</li>
        <li>Making false appeals to authority based on whoever made a post</li>
    </ul>
    You can still tell who is who on a per-thread basis by checking the "Posted by:" field - this
    is to prevent a single person from making intentionally weak arguments on a side they disagree
    with (a practice known as false-flagging) and for certain threads where the identity of a certain
    poster is important - if someone is relaying a live event, for example.
    </p>
    <h1 id="why-maniwani">Why Maniwani? There's other imageboards out there.</h1>
    <p class="lead">Maniwani's just better.</p>
    <p>But seriously, Maniwani has had a lot of thought and effort put into its design, especially
        on the visual side of things. If you're new to the concept of imageboards, you'll probably
        find Maniwani easier to get the hang of compared to the competition. It also makes sure not
        to leave mobile users out in the cold - the site was written from the ground up such that
        mobile users wouldn't need to use a 3rd-party client just to have an enjoyable experience on
        their phones and tablets!</p>
    <p>For the techies, Maniwani also includes a full REST API capable of doing anything the web frontend
        can do, in addition to gracefully downgrading if Javascript has been disabled.</p>
    <h1 id="what-topics">What topics can I talk about here?</h1>
    <p class="lead">Plenty!</p>
    <p>Go look at the <a href="{{ url_for("boards.list") }}">board listing</a> to get an idea of the sort of
        things you can talk about.</p>
</div>
{% endblock %}

templates/new-thread.html
{%- extends "base.html" %}
{% block head %}
	{% if config["USE_RECAPTCHA"] %}
		<script src='https://www.google.com/recaptcha/api.js?render={{ config["RECAPTCHA_SITE_KEY"] }}'></script>
	{% endif %}
{% endblock %}
{% block title %}
new thread
{% endblock %}
{% import "post-base.html" as post with context %}
{% block content %}
<div class="container">
    {{ post.post_form(url_for("threads.submit"), "board", board["id"], thread_op=True) }}
</div>
{% endblock %}

templates/react-board-index.html
{%- extends "base.html" %}
{% block title %}
	board index
{% endblock %}
{% block content %}
	<div class="container-fluid">
		TEMPLATE_CONTENT
	</div>
{% endblock %}